# Generated by Django 4.1.6 on 2023-09-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('numberOfPhone', models.CharField(max_length=13, verbose_name='Номер телефона')),
                ('date', models.DateField(verbose_name='Дата и время')),
                ('status', models.CharField(max_length=255, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
