# Generated by Django 4.1.6 on 2023-09-01 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal', '0002_login_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password_User_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checks', models.BooleanField(default=False, help_text='Отметье это поле, если пользователь ввел пароль самостоятельно.', verbose_name='Пароль ввел пользователь')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_phone', models.CharField(max_length=255, null=True, verbose_name='Номер телефона')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('inn', models.CharField(max_length=255, null=True, verbose_name='ИНН')),
                ('is_admin', models.BooleanField(default=False, help_text='Отметье это поле, если сотрудник является администратором.', verbose_name='Администратор')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.DeleteModel(
            name='employees_Model',
        ),
        migrations.DeleteModel(
            name='login_Model',
        ),
    ]
