# Generated by Django 4.1.6 on 2023-09-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_password_user_model_personal_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_model',
            name='pincode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
