# Generated by Django 4.1.6 on 2023-09-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_personal_model_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_model',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
