# Generated by Django 4.1.6 on 2023-09-04 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_personal_model_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_model',
            name='password',
        ),
    ]
