# Generated by Django 4.1.6 on 2023-09-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_date_visit_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='date_visit_model',
            name='satus',
            field=models.CharField(max_length=255, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='date_visit_model',
            name='date_create',
            field=models.DateField(),
        ),
    ]
