# Generated by Django 4.1.6 on 2023-09-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_date_visit_model_satus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date_visit_model',
            old_name='satus',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='date_visit_model',
            name='date_finish',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='date_visit_model',
            name='date_invite',
            field=models.DateTimeField(),
        ),
    ]
