# Generated by Django 4.1.6 on 2023-09-15 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal', '0009_rename_satus_date_visit_model_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date_visit_model',
            name='date_create',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='date_visit_model',
            name='date_finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='date_visit_model',
            name='date_invite',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='date_visit_model',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='date_visit_model',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitdate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='password_user_model',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personal_model',
            name='inn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='personal_model',
            name='number_of_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='personal_model',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
