# Generated by Django 4.1.6 on 2024-02-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_alter_date_visit_model_date_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_model',
            name='date_deactivate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
    ]
