# Generated by Django 4.1.6 on 2024-02-13 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0012_date_visit_model_pause_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date_visit_model',
            name='pause_time',
        ),
    ]
