# Generated by Django 4.1.6 on 2024-02-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0015_date_visit_model_summ_pause_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='date_visit_model',
            name='summ_work_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Общие отработанные часы'),
        ),
    ]
