# Generated by Django 4.1.6 on 2024-02-13 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0016_date_visit_model_summ_work_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date_visit_model',
            options={'ordering': ['-date_create'], 'verbose_name': 'Табель'},
        ),
    ]
