# Generated by Django 4.1.6 on 2024-02-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0017_alter_date_visit_model_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date_visit_model',
            name='status',
            field=models.CharField(blank=True, default='Не активен', max_length=255, null=True, verbose_name='Статус'),
        ),
    ]
