# Generated by Django 4.1.6 on 2024-02-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0019_organization_model_personal_model_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='date_visit_model',
            name='image',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
