# Generated by Django 4.1.6 on 2024-02-16 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0020_date_visit_model_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date_visit_model',
            name='image',
        ),
    ]
