# Generated by Django 4.1.6 on 2024-03-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0021_remove_date_visit_model_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='date_visit_model',
            name='geo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='date_visit_model',
            name='image_info',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
