# Generated by Django 4.1.6 on 2024-03-08 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0022_date_visit_model_geo_date_visit_model_image_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date_visit_model',
            options={'ordering': ['-date_create'], 'verbose_name': 'Табель', 'verbose_name_plural': 'Табели'},
        ),
    ]
