# Generated by Django 4.1.6 on 2024-03-08 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0023_alter_date_visit_model_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='password_user_model',
            options={'verbose_name': 'Проверка на ввод пароля пользователя', 'verbose_name_plural': 'Проверка на ввод паролей'},
        ),
    ]
